export { default as Background } from '~/components/Background'
export { default as Footer } from '~/components/Footer'
export { default as GalaxyThree } from '~/components/GalaxyThree'
export { default as Header } from '~/components/Header'
export { default as Loading } from '~/components/Loading'
